server:
  debug: false
  app_version: 1.0.0
  addr: :5000
  jwt_secret: accesskey
  jwt_refresh_secret: refreshkey

db:
  driver: postgres
  host: db
  port: 5432
  user: postgres
  password: postgres
  name: app
  ssl: disable

redis:
  addr: redis:6379
  password:
  db: 0

cookie:
  access_token:
    max_age: 300 # 5 minutes
    secure: false
    http_only: true

  refresh_token:
    max_age: 86400 # 24 hours
    secure: false
    http_only: true

logger:
  level:
